services:
  chrome-novnc:
    build: .
    environment:
      - VNC_TITLE=${VNC_TITLE-Chromium}
      - VNC_SHARED=${VNC_SHARED-false}
      - VNC_RESOLUTION=${VNC_RESOLUTION-1280x720}
      - PORT=8080
    ports:
      - "${HOST_PORT-8080}:8080/tcp"
      - "9222:9222"
    restart: always
