services:
  chrome-novnc:
    build: .
    environment:
      - VNC_TITLE=chrome-novnc-cdp
      - VNC_SHARED="true"
      - VNC_RESOLUTION=${VNC_RESOLUTION-1280x720}
      - PORT=9220
    ports:
      # novnc web client
      - "9220:9220"
      # browser control api
      - "9221:9221"
      # CDP port
      - "9222:9222"
